### ISSUE TITLE
mode16bit only works when invertedLogic is also true

### ISSUE THREAD

**Issue by HCNC1** [TcMenu/IoAbstraction#196]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if it is more than trival to set up the test for this, please include a sketch that recreates the problem.

**Expected behavior**

**Screenshots**

**Device and Environment**
Please include a complete breakdown of your board, attached hardware, developer environment etc.

**Additional context**

**Comment by vzahradnik** [comment]
Yes, I can confirm. I didn't observe this bug sooner because we were using the inverted logic (I originally implemented this). I'm working on a fix right now.

Currently we have a workaround:

```cpp
    // TODO: Use proper initialization for inputs
    for (size_t i = 0; i < 16; i++) {
        ioexp_digital_inputs->pinDirection(i, INPUT);
    }
```
